config/routes.rb
Rails.application.routes.draw do
  resources :g_forms do
    resources :responses
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "g_forms#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/g_form.rb
class GForm < ApplicationRecord
  has_many :questions, dependent: :destroy
  has_many :responses, dependent: :destroy
  has_one_attached :image, dependent: :destroy

  accepts_nested_attributes_for :questions, allow_destroy: true
end

app/models/option.rb
class Option < ApplicationRecord
  belongs_to :question
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :g_form
  has_many :options, dependent: :destroy
  has_one_attached :image, dependent: :destroy
  accepts_nested_attributes_for :options, allow_destroy: true
end

app/models/response.rb
class Response < ApplicationRecord
  belongs_to :g_form
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/g_forms_controller.rb
class GFormsController < ApplicationController
  before_action :set_g_form, only: %i[ show edit update destroy ]

  # GET /g_forms or /g_forms.json
  def index
    @g_forms =  GForm.includes(questions: [:options, { image_attachment: :blob }]).with_attached_image
  end

  # GET /g_forms/1 or /g_forms/1.json
  def show
  end

  # GET /g_forms/new
  def new
    @g_form = GForm.new
    @g_form.questions.build.options.build
  end

  # GET /g_forms/1/edit
  def edit
  end

  # POST /g_forms or /g_forms.json
  def create
    @g_form = GForm.new(g_form_params)

    respond_to do |format|
      if @g_form.save
        format.html { redirect_to g_form_url(@g_form), notice: "G form was successfully created." }
        format.json { render :show, status: :created, location: @g_form }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @g_form.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /g_forms/1 or /g_forms/1.json
  def update
    respond_to do |format|
      if @g_form.update(g_form_params)
        format.html { redirect_to g_form_url(@g_form), notice: "G form was successfully updated." }
        format.json { render :show, status: :ok, location: @g_form }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @g_form.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /g_forms/1 or /g_forms/1.json
  def destroy
    @g_form.destroy!

    respond_to do |format|
      format.html { redirect_to g_forms_url, notice: "G form was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_g_form
      @g_form = GForm.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def g_form_params
      params.require(:g_form).permit(:title, :description, :image, questions_attributes: [:title,  :type_of_question, :image, :_destroy, options_attributes: [:title, :_destroy]])
    end
end

app/controllers/responses_controller.rb
class ResponsesController < ApplicationController
  before_action :set_response, only: :show
  before_action :set_g_form, only: %i[new create index]

  def index
    @responses = @form.responses
  end

  def new
    @response = @form.responses.new
  end

  def show; end

  def create
    @response = @form.responses.new(response_params)
    if @response.save
      redirect_to g_form_response_path(@form, @response), notice: 'Response was successfully submitted.'
    else
      render :new, status: :unprocessable_entity
    end
  end


  private

  def response_params
    params.require(:response).permit(:sent_by, answers: {})
  end

  def set_g_form
    @form = GForm.find_by(id: params[:g_form_id])
  end

  def set_response
    @response = Response.find_by(id: params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/g_forms_helper.rb
module GFormsHelper
  def find_option(option_id)
    Option.find(option_id).title
  end

  def find_question(question_id)
    Question.find(question_id).title
  end

  def display_answer(question_id, answer)
    question = find_question(question_id)
    if question.type_of_question == 'multiselect'
      display_multiselect_answer(answer)
    elsif question.type_of_question == 'radio_button'
      display_radio_button_answer(answer)
    else
      answer
    end
  end

  def display_multiselect_answer(answer)
    options = Option.where(id: answer)
    options.map(&:title).join(', ')
  end

  def display_radio_button_answer(answer)
    Option.find(answer).title
  end
end

app/helpers/responses_helper.rb
module ResponsesHelper
  def find_question(question_id)
    Question.find(question_id).title
  end

  def display_answer(question_id, answer)
    question = Question.find(question_id)
    if question.type_of_question == 'multiselect'
      options = Option.where(id: answer)
      options.map(&:title).join(', ')
    elsif question.type_of_question == 'radio_button'
      Option.find_by(id: answer)&.title || answer
    else
      answer
    end
  end

  def render_question_options(question)
    return render_text_field(question) if question.options.empty?

    case question.type_of_question
    when 'multiselect'
      render_multiselect_options(question)
    when 'radio_button'
      render_radio_button_options(question)
    when 'text'
      render_text_field(question)
    when 'text_area'
      render_text_area(question)
    else
      ''
    end
  end

  private

  def render_multiselect_options(question)
    options_html = question.options.map do |option|
      checkbox_tag = check_box_tag "response[answers][#{question.id}][]", option.id, false, id: "response_#{question.id}_#{option.id}"
      label_tag = label_tag "response_#{question.id}_#{option.id}", option.title, for: "response_#{question.id}_#{option.id}"
      content_tag(:div, checkbox_tag + label_tag)
    end
    options_html.join('').html_safe
  end

  def render_radio_button_options(question)
    options_html = question.options.map do |option|
      radio_button_tag = radio_button_tag "response[answers][#{question.id}]", option.id, false, id: "response_#{question.id}_#{option.id}"
      label_tag = label_tag "response_#{question.id}_#{option.id}", option.title, for: "response_#{question.id}_#{option.id}"
      content_tag(:div, radio_button_tag + label_tag)
    end
    options_html.join('').html_safe
  end

  def render_text_field(question)
    text_field_tag "response[answers][#{question.id}]", nil
  end

  def render_text_area(question)
    text_area_tag "response[answers][#{question.id}]", nil
  end
end

app/views/g_forms/_form.html.erb
<%= form_with(model: g_form) do |form| %>
  <% if g_form.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(g_form.errors.count, "error") %> prohibited this g_form from being saved:</h2>

      <ul>
        <% g_form.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description %>
  </div>

    <div>
    <%= form.label :image, style: "display: block" %>
    <%= form.file_field :image %>
  </div>

  <div class="questions">
    <% form.fields_for :questions do |form| %>
      <%= render 'question_fields', form: form %>
    <% end %>
  </div>
  <div class="links">
    <%= link_to_add_association "add questions", form, :questions, form_name: 'form' %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/g_forms/_g_form.html.erb
<h1><%= g_form.title %></h1>
<p><%= g_form.description %></p>

<%= link_to 'Share Form', new_g_form_response_path(g_form) %>

<h2>Responses</h2>
<table>
  <thead>
    <tr>
      <th>Respondent</th>
      <% g_form.questions.each do |question| %>
        <th>Question : <%= question.title %></th>
      <% end %>
    </tr>
  </thead>
  <tbody>
    <% g_form.responses.each do |response| %>
      <tr>
        <td><%= response.sent_by %></td>
        <% response.answers.each do |question_id, answer| %>
          <td><%= display_answer(question_id, answer) %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/g_forms/_option_fields.html.erb
<div class="nested-fields">
  <%= form.label :title %>
  <%= form.text_field :title %>
  <%= link_to_remove_association "Remove Option", form %>
</div>

app/views/g_forms/_question_fields.html.erb
<div class="nested-fields">
  <%= form.label :title %>
  <%= form.text_field :title %>

  <%= form.label :type_of_question %>
  <%= form.select :type_of_question, [['Radio button', 'radio_button'], ['Multiselect', 'multiselect'], ['Text', 'text'], ['Text area', 'text_area']], {} %>

  <%= form.label :image %>
  <%= form.file_field :image %>

  <h4>Options</h4>
  <div id="options">
    <%= form.fields_for :options do |option_form| %>
      <%= render 'option_fields', form: option_form, type_of_question: form.object.type_of_question %>
    <% end %>
    <div class="links">
      <%= link_to_add_association 'Add Option', form, :options, form_name: 'form', data: { type_of_question: '' } %>
    </div>
  </div>
  <%= link_to_remove_association "remove question", form %>
</div>

app/views/g_forms/edit.html.erb
<h1>Editing g form</h1>

<%= render "form", g_form: @g_form %>

<br>

<div>
  <%= link_to "Show this g form", @g_form %> |
  <%= link_to "Back to g forms", g_forms_path %>
</div>

app/views/g_forms/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>G forms</h1>

<div id="g_forms">
  <% @g_forms.each do |g_form| %>
    <%= render g_form %>
    <p>
      <%= link_to "Show this g form", g_form %>
    </p>
  <% end %>
</div>

<%= link_to "New g form", new_g_form_path %>

app/views/g_forms/new.html.erb
<h1>New g form</h1>

<%= render "form", g_form: @g_form %>

<br>

<div>
  <%= link_to "Back to g forms", g_forms_path %>
</div>

app/views/g_forms/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @g_form %>

<div>
  <%= link_to "Edit this g form", edit_g_form_path(@g_form) %> |
  <%= link_to "Back to g forms", g_forms_path %> |
  <%= link_to "Responses", g_form_responses_path(@g_form)%>

  <%= button_to "Destroy this g form", @g_form, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GoogleForm</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "jquery" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/responses/_response.html.erb
<div>
  <h3>Response from <%= response.sent_by %></h3>
  <table>
    <thead>
      <tr>
        <th>Question</th>
        <th>Answer</th>
      </tr>
    </thead>
    <tbody>
      <% response.answers.each do |question_id, answer| %>
        <tr>
          <td><%= find_question(question_id) %></td>
          <td><%= display_answer(question_id, answer) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<%= link_to "Back to g forms", g_forms_path %> |

app/views/responses/index.html.erb
<h2>Responses</h2>
<% @responses.each do |response|%>
	<%= render 'response', response: response%>
<% end %>

app/views/responses/new.html.erb
<%= form_with(model: [@form, @response], local: true) do |form| %>
  <%= form.label :sent_by %>
  <%= form.text_field :sent_by %>

  <% @form.questions.each do |question| %>
    <div>
      <h4><%= question.title %></h4>
      <%= render_question_options(question) %>
    </div>
  <% end %>

  <%= form.submit 'Submit Response' %>
<% end %>

app/views/responses/show.html.erb
<%= render 'response', response: @response%>